name: .NET CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore BugStore.sln
        working-directory: ./src

      - name: Build
        run: dotnet build BugStore.sln --no-restore
        working-directory: ./src

      - name: Test
        run: dotnet test BugStore.sln --no-build --verbosity normal
        working-directory: ./src

      - name: Publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/BugStore.Api

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bugstore-api
          path: ./src/BugStore.Api/publish
